-- =============================================================================
-- Duble Slash — Outreach: import 40 design leaders from Tal's LinkedIn
-- connections (linkedin_profiles.csv). All are in-house leaders at product
-- companies, so contact_type = 'company'. Priority assigned by seniority:
--   P0  = VP / SVP / Head / Director / Principal / Senior Director
--   P1  = Lead / Manager / Group Manager / Team Lead / Team Manager
--   P2  = Senior IC / other
--
-- One existing row (Adi Rozen Benvenisti, id 'adi-rozen-benvenisti') is
-- updated with the richer CSV note; the other 39 rows are new inserts.
--
-- Fully idempotent. Single quotes inside notes are doubled per SQL rules.
-- =============================================================================

insert into public.outreach_contacts
  (id, contact_type, name, role, company, linkedin, company_url, stage_id, owner_id, priority_id, notes, sort_order)
values
  ('dvir-isac',            'company', 'Dvir Isac',            'Head of UX/UI',                                      'qbiq',                              'https://www.linkedin.com/in/dvir-isac-8480b062/',        null,                            'research', 'tal', 'p0', null,                                                                                                                                                       300),
  ('tom-abramovich',       'company', 'Tom Abramovich',       'Product Design Team Lead',                           'Moon Active',                       'https://www.linkedin.com/in/tom-abramovich-1662a4177/',  'https://www.moonactive.com',    'research', 'tal', 'p1', 'Leads product design team at a gaming company; previously at ONE ZERO and Skai.',                                                                         310),
  ('sarit-bartov',         'company', 'Sarit Bartov',         'Product Design Lead',                                'Zorro',                             'https://www.linkedin.com/in/sarit-bartov/',              'https://www.getzorro.com',      'research', 'tal', 'p1', 'Leads design using AI to simplify health insurance navigation for employees, employers & brokers. Previously 6 yrs at monday.com Growth.',              320),
  ('guy-greenhut',         'company', 'Guy Greenhut',         'Senior Product Design Group Manager',                'Monday.com',                        'https://www.linkedin.com/in/guygreenhut/',               'https://monday.com',            'research', 'tal', 'p1', 'Owns end-to-end product design strategy for Monday AI offering, including Sidekick, marketplace & multi-product suite.',                                 330),
  ('erez-reznikov',        'company', 'Erez Reznikov',        'Senior Product Designer & Design System Lead',       'Torq',                              'https://www.linkedin.com/in/erez-reznikov/',             'https://www.torq.io',           'research', 'tal', 'p2', 'Senior product designer and design systems expert at a cybersecurity unicorn.',                                                                            340),
  ('rottem-shaul',         'company', 'Rottem Shaul',         'Design Team Lead',                                   'Dream Security',                    'https://www.linkedin.com/in/rottem-shaul-39600764/',     'https://www.dream.security',    'research', 'tal', 'p1', 'Leads design team at a cybersecurity company.',                                                                                                            350),
  ('yael-turgeman',        'company', 'Yael Turgeman',        'Director of Product Design',                         'Lusha',                             'https://www.linkedin.com/in/yael-turgeman-81039954/',    'https://www.lusha.com',         'research', 'tal', 'p0', 'Directs product design at a B2B sales intelligence platform. Previously Product Design Group Manager at monday.com.',                                   360),
  ('omer-morag',           'company', 'Omer Morag',           'Senior Product Designer',                            'JFrog',                             'https://www.linkedin.com/in/omer-morag/',                'https://www.jfrog.com',         'research', 'tal', 'p2', 'Designs for Artifactory. Also a UX lecturer at the Technion. Passionate about simplifying complex DevOps systems.',                                      370),
  ('hadas-antebi',         'company', 'Hadas Antebi',         'Product Design Manager',                             'Redis',                             'https://www.linkedin.com/in/hadas-antebi-44579284/',     'https://www.redis.com',         'research', 'tal', 'p1', 'Manages product design at Redis (in-memory data platform).',                                                                                              380),
  ('yair-ronen',           'company', 'Yair Ronen',           'Principal Design & Research Manager',                'Microsoft',                         'https://www.linkedin.com/in/yairronen/',                 'https://www.microsoft.com',     'research', 'tal', 'p0', 'Leads the Azure design team in Israel, managing designers, researchers & content designers across Cloud Monitoring, Marketplace, Networking Security, and Media+AI.', 390),
  ('eyal-fendell',         'company', 'Eyal Fendell',         'Director of Product Design Platform & AI',           'Tipalti',                           'https://www.linkedin.com/in/eyalfendell/',               'https://www.tipalti.com',       'research', 'tal', 'p0', 'Leads design for platform & AI at a global AP automation company. Previously Head of UX at OpenText driving GenAI integration.',                          400),
  ('lior-kadishev',        'company', 'Lior Kadishev',        'Product Design Lead',                                'Karma',                             'https://www.linkedin.com/in/liorkadishev/',              'https://www.karmanow.com',      'research', 'tal', 'p1', 'Oversees the entire product creation process for the Karma shopping app. Promoted to lead in Jan 2026.',                                                 410),
  ('bar-gershoni',         'company', 'Bar Gershoni',         'Product Design Manager',                             'Phenom',                            'https://www.linkedin.com/in/bargershoni/',               'https://www.phenom.com',        'research', 'tal', 'p1', 'Manages design at a talent experience platform. Leads cross-functional teams and product lifecycle for 7+ years.',                                       420),
  ('avi-dantess',          'company', 'Avi Dantess',          'Director of Product Design',                         'AppsFlyer',                         'https://www.linkedin.com/in/avi-dantess/',               'https://www.appsflyer.com',     'research', 'tal', 'p0', 'Directs product design at a mobile attribution & marketing analytics company. Champions AI-first design. 10+ years in B2B SaaS.',                         430),
  ('dana-dotan',           'company', 'Dana Dotan',           'Head of UX & UI',                                    'eOS (esh Group)',                   'https://www.linkedin.com/in/dana-dotan-09a9b528/',       'https://www.esh.com',           'research', 'tal', 'p0', 'Built the design org from scratch (12+ people). Leads B2B banking interfaces and B2C digital banking experiences for a next-gen banking platform.',     440),
  ('roi-atias',            'company', 'Roi Atias',            'Product Design Lead',                                'Monday.com',                        'https://www.linkedin.com/in/roi-atias-80366751/',        'https://monday.com',            'research', 'tal', 'p1', 'Leads product design. Previously built and managed the design team at Workiz SaaS for 4 years.',                                                         450),
  ('idan-segev',           'company', 'Idan Segev',           'VP of Product Design',                               'Tipalti',                           'https://www.linkedin.com/in/idansegev/',                 'https://www.tipalti.com',       'research', 'tal', 'p0', 'VP leading design at a global fintech/AP automation platform. Previously Design Group Manager at Intuit (QuickBooks AP) and Director of UX at Moovit.', 460),
  ('federico-dayan',       'company', 'Federico Dayan',       'Head of Product Design',                             'Gett',                              'https://www.linkedin.com/in/fede-dayan/',                'https://www.gett.com',          'research', 'tal', 'p0', 'Heads design at a B2B ride-hailing platform. Focuses on how design teams make decisions. Founder of Sketch & Behance Israeli communities.',              470),
  ('hen-shkedi',           'company', 'Hen Shkedi',           'Senior Director of Product Design',                  'Cloudinary',                        'https://www.linkedin.com/in/shkedi/',                    'https://www.cloudinary.com',    'research', 'tal', 'p0', 'Senior Director of Product Design at a leading media management cloud platform.',                                                                         480),
  ('nimrod-dado',          'company', 'Nimrod Dado',          'Senior Product Design Group Manager',                'Monday.com',                        'https://www.linkedin.com/in/nimrodado/',                 'https://monday.com',            'research', 'tal', 'p1', 'Senior design group manager focusing on Growth. Previously at Meta (Facebook Financials & Connectivity) and Wix.',                                       490),
  ('erez-dagan',           'company', 'Erez Dagan',           'Product Design Lead',                                'Base44',                            'https://www.linkedin.com/in/erez-dagan/',                'https://www.base44.com',        'research', 'tal', 'p1', 'Leads product design at an AI app-building platform. Previously UX Team Lead at Wix for Vibe and Automations.',                                          500),
  ('einav-kivshany',       'company', 'Einav Kivshany',       'Product Design Team Lead',                           'WSC Sports',                        'https://www.linkedin.com/in/ekivshany/',                 'https://www.wscsports.com',     'research', 'tal', 'p1', 'Leads design at a sports media AI platform. Previously Principal Design Lead at Autodesk for 9+ years.',                                                 510),
  ('ran-liron',            'company', 'Ran Liron',            'Director of Product Design',                         'XM Cyber',                          'https://www.linkedin.com/in/ranliron/',                  'https://www.xmcyber.com',       'research', 'tal', 'p0', 'Directs product design at a cybersecurity (exposure management) company.',                                                                                520),
  ('omri-dvir',            'company', 'Omri Dvir',            'Director of Product Design',                         'Payoneer',                          'https://www.linkedin.com/in/omri-dvir-40723652/',        'https://www.payoneer.com',      'research', 'tal', 'p0', 'Directs product design at a global payments platform.',                                                                                                    530),
  ('or-froind',            'company', 'Or Froind',            'Innovator',                                          'Holon Municipality',                'https://www.linkedin.com/in/or-froind/',                 'https://www.holon.muni.il',     'research', 'tal', 'p2', 'Part-time design innovator at a city municipality. Also runs freelance UI/UX & branding practice for 16+ years.',                                      550),
  ('michal-turjeman',      'company', 'Michal Turjeman',      'VP Design',                                          'Minute Media',                      'https://www.linkedin.com/in/michal-turjeman-b92b0847/',  'https://www.minutemedia.com',   'research', 'tal', 'p0', 'Leads design at a global sports media company (formerly 90min). Responsible for B2B & B2C products across platforms for 11+ years.',                     560),
  ('lihi-ashkenazi',       'company', 'Lihi Ashkenazi',       'Design Manager',                                     'Meta',                              'https://www.linkedin.com/in/lihi-ashkenazi-2938a256/',   'https://www.meta.com',          'research', 'tal', 'p1', 'Manages design at Meta (Israel). Previously Director of Product Design at Yotpo.',                                                                        570),
  ('miki-chernyak',        'company', 'Miki Chernyak',        'Product Design Lead',                                'Twine Security',                    'https://www.linkedin.com/in/product-hero/',              'https://www.twinesecurity.com', 'research', 'tal', 'p1', 'Leads design at an AI-powered cybersecurity startup. Formerly at Salto and Wix (Editor X). Also a Figma course creator.',                                 580),
  ('julia-budiansky',      'company', 'Julia Budiansky',      'Design Manager',                                     'Zenity',                            'https://www.linkedin.com/in/julia-budiansky/',           'https://www.zenity.io',         'research', 'tal', 'p1', 'Design manager at an agentic AI security company.',                                                                                                        590),
  ('tal-solomon-vardy',    'company', 'Tal Solomon Vardy',    'Product Design Lead',                                'Prime Security',                    'https://www.linkedin.com/in/talsolomonvardy/',           'https://www.primesec.ai',       'research', 'tal', 'p1', 'Leads design at a cybersecurity SaaS startup. 10+ years in B2B cybersecurity UX. Also Founder & Editor of Uncoated Magazine.',                           600),
  ('orit-miller',          'company', 'Orit Miller',          'Product Design Team Manager',                        'Similarweb',                        'https://www.linkedin.com/in/orit-miller-305a26122/',     'https://www.similarweb.com',    'research', 'tal', 'p1', 'Manages product design team at a digital intelligence company.',                                                                                          610),
  ('tzipora-reiner',       'company', 'Tzipora Reiner',       'Product Design Lead',                                'justt',                             'https://www.linkedin.com/in/tzipora-reiner-4650b5140/',  'https://www.justt.ai',          'research', 'tal', 'p1', 'Leads product design at an AI-powered chargeback mitigation fintech.',                                                                                    620),
  ('saar-gil',             'company', 'Saar Gil',             'Design Team Lead',                                   'eOS (esh Group)',                   'https://www.linkedin.com/in/saargil/',                   'https://www.esh.com',           'research', 'tal', 'p1', 'Leads 4-person design team at a cloud-native agentic banking platform. Also Founder of Design Club (workshops, podcast, meetups).',                    630),
  ('rei-ayal',             'company', 'Rei Ayal',             'Product Design Lead',                                'Facts Commando',                    'https://www.linkedin.com/in/reiayaldesign/',             null,                            'research', 'tal', 'p1', 'Product design lead (also does freelance work).',                                                                                                           640),
  ('hadas-yarkoni',        'company', 'Hadas Yarkoni',        'Product Design Lead',                                'Stream.Security',                   'https://www.linkedin.com/in/hadas-yarkoni/',             'https://www.stream.security',   'research', 'tal', 'p1', 'Leads product design at a cloud security platform.',                                                                                                       650),
  ('lupo-asaf',            'company', 'Lupo Asaf',            'Product Design Group Manager',                       'Check Point Software Technologies', 'https://www.linkedin.com/in/lupo-asaf-55150224/',        'https://www.checkpoint.com',    'research', 'tal', 'p1', 'Manages product design group at a global cybersecurity company. Previously Head of Design at Code Ocean.',                                               660),
  ('anna-bloom',           'company', 'Anna Bloom',           'Design Manager',                                     'AT&T',                              'https://www.linkedin.com/in/anna-bloom1/',               'https://www.att.com',           'research', 'tal', 'p1', 'Manages design team at the global telecom. UX Lead for 4+ years previously. Also mentor and speaker.',                                                    670),
  ('vitaly-mijiritsky',    'company', 'Vitaly Mijiritsky',    'UX Lead & UX Research Academic Director',            'HP / Technion',                     'https://www.linkedin.com/in/vitalymijiritsky/',          'https://www.hp.com',            'research', 'tal', 'p0', 'UX Lead at HP Indigo and Academic Director of UX Research at the Technion. Ex-Google for Startups UX Mentor. Steering committee member of UXI Live.', 680),
  ('josh-milwer',          'company', 'Josh Milwer',          'Design Lead',                                        'Briya',                             'https://www.linkedin.com/in/joshmv/',                    'https://www.briya.com',         'research', 'tal', 'p1', 'Leads design at an AI-powered medical research platform (AIRE). Previously at Microsoft (AI Hive, Teams Premium) and General Motors (in-vehicle AI UX).', 690)
on conflict (id) do nothing;

-- Enrich Adi's existing row with the CSV's richer description.
update public.outreach_contacts
  set role = 'Director of Product Design',
      notes = 'Leads 30+ person design org (CX, UX, Research, UI) at Israel''s largest bank. Co-created the ''bit'' payment app from the ground up.'
  where id = 'adi-rozen-benvenisti';
